fix: do not import in close, we get called during garbage collection
I see in solara:
Exception ignored in: <function BaseComm.__del__ at 0x111534430>
Traceback (most recent call last):
  File "/Users/maartenbreddels/github/3rd/comm/comm/base_comm.py", line 64, in __del__
  File "/Users/maartenbreddels/github/3rd/comm/comm/base_comm.py", line 95, in close
ImportError: sys.meta_path is None, Python is likely shutting down

If instead, we call comm.get_comm_manager we still always
get the latest get_comm_manager, but do not do an import at during
garbage collection.